{% set name = "deepinv" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/deepinv/deepinv/archive/v{{ version }}.tar.gz
  sha256: 376a6272a7a58932c42fbaf9747b40c28a1e8fd7648b42d8bc384e3af44cb6e0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - matplotlib-base
    - h5py
    - tqdm
    - pytorch >=2.2.0
    - torchvision
    - torchmetrics
    - einops
    - scipy
    - natsort

test:
  imports:
    - deepinv
  commands:
    - pip check
    #- pytest deepinv/tests -v -k "not test_ncsnpp_net" -k "test_algo_inpaint and not DDRM"
    - pytest deepinv/tests -v -k "not (test_load_ or test_icnn or test_ncsnpp_net or test_algo_inpaint or test_datasets or test_denoiser_perf)" -m "not slow"
  source_files:
    - deepinv/tests/*
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - datasets
    - ipython
    - timm
    - pywavelets
    - kornia
    - torchkbnufft
    - sigpy
    - mat73

about:
  summary: Pytorch library for solving inverse problems with deep learning
  dev_url: https://github.com/deepinv/deepinv
  home: https://github.com/deepinv/deepinv
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - gschramm
    - tachella
    - matthieutrs
